import { chromium } from "@playwright/test";
const b = await (async () => { try { return await chromium.launch({ channel: "chrome" }) } catch { return await chromium.launch() } })();
const ctx = await b.newContext();
const p = await ctx.newPage();
await p.addInitScript(() => localStorage.setItem("setting:filmStripSectionDots", "1"));
await p.goto("http://127.0.0.1:8766/ui/settings", { waitUntil: "networkidle" });
await p.waitForTimeout(800);
const clicked = await p.evaluate(() => {
  const labels = [...document.querySelectorAll("label.toggle")];
  const target = labels.find((l) => (l.parentElement?.textContent || "").includes("题库条显示分类颜色"));
  if (!target) return "not-found";
  const input = target.querySelector("input");
  input?.click();
  return input?.checked;
});
console.log("clicked -> new checked:", clicked, "ls =", await p.evaluate(() => localStorage.getItem("setting:filmStripSectionDots")));
await p.waitForTimeout(300);
await p.goto("http://127.0.0.1:8766/ui/filter", { waitUntil: "networkidle" });
await p.waitForTimeout(1200);
console.log("filter dots after OFF:", await p.locator(".ws-filmstrip .fs-item-dot").count());
await p.goto("http://127.0.0.1:8766/ui/compose", { waitUntil: "networkidle" });
await p.waitForTimeout(1500);
console.log("compose bank items:", await p.locator(".bank-item").count(), "dots:", await p.locator(".bank-item-dot").count());
await b.close();
